version: '2'

volumes:
  mariadb:
  solr:

services:
  # Apache 2.4
  web:
    build:
      context: .
      dockerfile: buildfiles/apache-2.4/Dockerfile.apache-2.4
    volumes:
     - /srv/www:/srv/www:delegated
     - /home/webspace:/home/webspace
     - ./config/apache-2.4:/etc/apache2
     - ./persistent/logs/apache:/var/log/apache2
    ports:
      - 80:80
      - 443:443
    links:
       - php-fpm-7.4
       - php-fpm-8.0
    environment:
      APACHE_RUN_USER: "${WWWUID}"
      APACHE_RUN_GROUP: "${WWWUID}"
      APACHE_LOG_DIR: "/var/log/apache2"
      DOCKERHOSTIP: "172.17.0.1"

  # Mailcatcher
  mailcatcher:
    image: schickling/mailcatcher
    user: "${UID}"
    ports:
      - 1080:1080

  # Maria DB
  db:
    image: mariadb:latest
    volumes:
     - mariadb:/var/lib/mysql
     - ./config/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

  # Solr 4
  solr4:
    image: geerlingguy/solr:4.x
    volumes:
      - solr:/var/solr/cores
    ports:
      - 8983:8983
    command: ["/opt/solr/bin/solr", "start", "-p", "8983", "-s", "/var/solr", "-f"]
    restart: always
    extra_hosts:
      - "DOCKERHOSTIP:172.17.0.1"
    environment:
      DOCKERHOSTIP: "172.17.0.1"

  # Tika
  tika:
    image: logicalspark/docker-tikaserver
    user: "${WWWUID}"
    ports:
      - 9998:9998
    restart: always
    extra_hosts:
      - "DOCKERHOSTIP:172.17.0.1"
    environment:
      DOCKERHOSTIP: "172.17.0.1"

  # Php FPM
  php-fpm-7.4:
    build:
      context: .
      dockerfile: buildfiles/php-fpm-7/Dockerfile.php-fpm-7.4
    volumes:
     - /srv/www:/srv/www:delegated
     - ./config/php-fpm-7/php.ini:/usr/local/etc/php/php.ini
     - ./config/php-fpm-7/www.conf:/usr/local/etc/php-fpm.d/www.conf
     - solr:/var/solr/cores
     - ./config/msmtp/msmtprc:/etc/msmtprc
     - ./faketimerc:/etc/faketimerc
    restart: always
    user: "${WWWUID}"
    links:
      - db
      - mailcatcher
      - solr4
    depends_on:
      - db
    extra_hosts:
      - "DOCKERHOSTIP:172.17.0.1"
    environment:
      DOCKERHOSTIP: "172.17.0.1"
    cap_add:
      - SYS_PTRACE

  php-fpm-8.0:
    build:
      context: .
      dockerfile: buildfiles/php-fpm-8/Dockerfile.php-fpm-8.0
    volumes:
     - /srv/www:/srv/www:delegated
     - ./config/php-fpm-8/php.ini:/usr/local/etc/php/php.ini
     - ./config/php-fpm-8/www.conf:/usr/local/etc/php-fpm.d/www.conf
     - solr:/var/solr/cores
     - ./config/msmtp/msmtprc:/etc/msmtprc
     - ./faketimerc:/etc/faketimerc
    restart: always
    user: "${WWWUID}"
    links:
      - db
      - mailcatcher
      - solr4
    depends_on:
      - db
    extra_hosts:
      - "DOCKERHOSTIP:172.17.0.1"
    environment:
      DOCKERHOSTIP: "172.17.0.1"
    cap_add:
      - SYS_PTRACE
