#!/bin/bash

suites="$@"
if [ ! "$suites" ]
    then echo "Specify behat suite(s) to run e.g. asset-admin" && return
fi

if [ -d artifacts ]
  then rm -rf artifacts
fi
mkdir artifacts

echo 'Killing any old chromedriver instances.'
docker exec -t --workdir /var/www -u 1000 ${PROJECT_NAME}_webserver DRIVER_PID=$(pgrep chromedriver); if [ -n "$DRIVER_PID" ]; then kill -15 $DRIVER_PID > /dev/null; fi
echo 'Starting up chromedriver.'
docker exec -t --workdir /var/www -u 1000 ${PROJECT_NAME}_webserver nohup sh -c "chromedriver --log-path=artifacts/chromedriver.log --log-level=INFO" > /dev/null 2>&1 &
docker exec -t --workdir /var/www -u 1000 ${PROJECT_NAME}_webserver env TERM=xterm-256color bash -c "vendor/bin/behat --tags=gsat $suites"
