#!/bin/bash

# Mailhog - will install binaries to /home/www-data/go/bin
# ${PROJECT_NAME}:8025 for dashboard
runuser -l www-data -c 'go get github.com/mailhog/MailHog'
runuser -l www-data -c 'go get github.com/mailhog/mhsendmail'
runuser -l www-data -c 'nohup sh -c "/home/www-data/go/bin/MailHog" > /dev/null 2>&1 &'

# Apache gets grumpy about PID files pre-existing, so remove them:
rm -f /var/run/apache2/apache2.pid

# Read default envvars, which includes APACHE_RUN_USER/GROUP=www-data
source /etc/apache2/envvars

# Start apache
# It seems like -DFOREGROUND is required for the container to work correctly
exec /usr/sbin/apache2ctl -DFOREGROUND
