#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use DevTools\Command\CreateEnv;
use DevTools\Command\DestroyEnv;
use DevTools\Command\Docker;
use DevTools\Command\Sake;
use DevTools\Utility\Config;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputDefinition;
use Symfony\Component\Console\Input\InputOption;

set_time_limit(0);

Config::init();

$application = new Application('Dev Tools');

// Remove a bunch of unnecessary options (verbose, version, etc)
$application->setDefinition(
    new InputDefinition([
        new InputArgument('command', InputArgument::REQUIRED, 'The command to execute'),
        new InputOption('--quiet', '-q', InputOption::VALUE_NONE, 'Do not output any message'),
        new InputOption(
            '--help',
            '-h',
            InputOption::VALUE_NONE,
            'Display help for the given command. When no command is given display help for the <info>list</info> command'
        ),
    ])
);

// Add custom commands
$application->addCommands([
    new CreateEnv(),
    new DestroyEnv(),
    new Docker(),
    new Sake(),
]);

// start
$application->run();
