#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use DevTools\Command;
use DevTools\Utility\Config;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputDefinition;
use Symfony\Component\Console\Input\InputOption;

set_time_limit(0);

Config::init();

$application = new Application('Dev Tools');

// Remove a bunch of unnecessary options (verbose, version, etc)
$application->setDefinition(
    new InputDefinition([
        new InputArgument('command', InputArgument::REQUIRED, 'The command to execute'),
        new InputOption('--quiet', '-q', InputOption::VALUE_NONE, 'Reduce verbosity of messages'),
        new InputOption('--verbose', '-v', InputOption::VALUE_NONE, 'Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug'),
        new InputOption(
            '--help',
            '-h',
            InputOption::VALUE_NONE,
            'Display help for the given command. When no command is given display help for the <info>list</info> command'
        ),
    ])
);

// Add custom commands
$application->addCommands([
    new Command\CLI\AddComposerPullRequest(),
    new Command\CLI\GitSetRemotes(),
    new Command\Env\Up(),
    new Command\Env\Down(),
    new Command\Env\Attach(),
    new Command\Env\Detach(),
    new Command\Env\Info(),
    new Command\Env\PhpConfig(),
    new Command\Execute\Docker(),
    new Command\Execute\Sake(),
    new Command\Test\Behat(),
    new Command\Database\Dump(),
]);

// start
$application->run();
