# sink_4-x_14 example:
# webserver:  10.0.14.50
# database:   10.0.14.51 root:root
# phpmyadmin: 10.0.14.52 root:root

# ssh
# docker exec -it ${PROJECT_NAME}_webserver sh -c "cd /var/www && su -s /bin/bash www-data"

# mysql
# mysql -h0.0.0.0 -P33${SUFFIX} -DSS_mysite -uroot -proot

# if docker complains about the "version" not being supported, then install that latest version of docker-compose
# https://docs.docker.com/compose/install/

version: '3.8'

services:

  webserver:
    container_name: ${PROJECT_NAME}_webserver
    image: gsartorelli/webserver
    build: .
    volumes:
      - ../www/:/var/www
      - ../logs/:/var/log
    domainname: ${HOST_SUFFIX}
    hostname: ${PROJECT_NAME}
    environment:
      APACHE_LOG_DIR: "/var/log/apache2"
    networks:
      mynet:
        ipv4_address: ${IP_PREFIX}.50

  mariadb:
    container_name: ${PROJECT_NAME}_mariadb
    image: mariadb:10.5.2
    # If changing database version after a container has already been created
    # it seems necessary to run something like `dqx` and rebuild everything.
    # image: mariadb:10.1.10
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "Pacific/Auckland"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: 'SS_mysite'
    # use ports instead of IP address for database connection
    # example: sink_4-x_14 connect on 0.0.0.0:3314
    ports:
      - 33${SUFFIX}:3306
    networks:
      mynet:

volumes:
  mariadb-volume:
    name: ${PROJECT_NAME}_mariadb-volume

networks:
  mynet:
    name: ${PROJECT_NAME}_mynet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_PREFIX}.0/24

# (will automatically create a ${PROJECT_NAME}_default network, name is based on the directory)

# If you get "cannot create network" issues - probably need to remove previously created stuff on the network:
# docker ps -a
# docker network ls
# https://stackoverflow.com/questions/45648821/docker-compose-up-error-invalid-address
# remove all containers
# docker rm -f $(docker ps -aq)
# remove all unused networks
# docker network prune -f

#ports:
  # Specify "- 80" instead of "- 80:80" to support multiple docker-composes
  # Docker compose will auto-generate a 0.0.0.0:327xx port
  # This is to solve "Bind for 0.0.0.0:80 failed: port is already allocated"
  # https://github.com/docker/compose/issues/4950#issuecomment-342882168
#  - 80
