# sink_4-x_14 example:
# webserver:  10.0.14.50
# database:   10.0.14.51 root:root
# phpmyadmin: 10.0.14.52 root:root

# mailhog
# http://${PROJECT_NAME}:8025

# ssh
# docker exec -it ${PROJECT_NAME}_webserver sh -c "cd /var/www && su -s /bin/bash www-data"

# mysql
# mysql -h0.0.0.0 -P33${SUFFIX} -DSS_mysite -uroot -proot

version: '3.8'

services:

  webserver:
    container_name: ${PROJECT_NAME}_webserver
    image: gsartorelli/webserver
    build: .
    volumes:
      - ../www/:/var/www
      - ../logs/:/var/log
      - ~/.cache/composer:/home/www-data/.cache/composer
    domainname: ${HOST_SUFFIX}
    hostname: ${PROJECT_NAME}
    environment:
      APACHE_LOG_DIR: "/var/log/apache2"
    networks:
      mynet:
        ipv4_address: ${IP_PREFIX}.50

  mariadb:
    container_name: ${PROJECT_NAME}_mariadb
    image: mariadb:10.5.2
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "Pacific/Auckland"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: 'SS_mysite'
    # use ports instead of IP address for database connection
    # example: sink_4-x_14 connect on 0.0.0.0:3314
    ports:
      - 33${SUFFIX}:3306
    networks:
      mynet:

volumes:
  mariadb-volume:
    name: ${PROJECT_NAME}_mariadb-volume

networks:
  mynet:
    name: ${PROJECT_NAME}_mynet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_PREFIX}.0/24
